# Generated by Django 5.1.4 on 2024-12-21 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_alter_blog_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='blog',
        ),
        migrations.AddField(
            model_name='tag',
            name='blog',
            field=models.ManyToManyField(related_name='tags', to='blog.blog'),
        ),
    ]
